---
name: 'Try Git Push'
on: [push]

jobs:
  push:
    runs-on: ubuntu-latest
    if: ! contains(github.event.head_commit.message, '[ci skip]')
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
          git config --global user.email "john.doe@example.com"
          git config --global user.name "john doe"

      - name: Commit
        run: |
          echo ${{ github.sha }} >> history
          git add history
          git commit -m 'add history [ci skip]'
          git push origin master
